services:
  web:
    build: .
    command: sh -c "python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    container_name: carPrice_app